image:
  file: .gitpod.Dockerfile

tasks:
  - init: make init
  - command: hugo server --baseUrl $(gp url 1313) --appendPort=false
    name: Hugo
    openMode: tab-before

ports:
  - port: 1313
    onOpen: open-preview
